name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            ghcr.io/5hoei/bookinfo-ratings:dev
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
            ghcr.io/5hoei/bookinfo-ratings:dev
          
      
      
      - run: docker build -t ghcr.io/5hoei/bookinfo-ratings:dev .
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker push ghcr.io/5hoei/bookinfo-ratings:dev